function f = synobj(x, sz, freqs, err)
    G = casctran(x, sz);
    % H = tsc(G, sz);
    S1 = sparameters(freqresp(G{1}, freqs), freqs);
    S2 = sparameters(freqresp(G{2}*1e3, freqs), freqs);
    % F = freqresp(H, freqs);
    F = cascadesparams(S1, S2);
    U = [squeeze(abs(F.Parameters(1,1,:)))' ...
         squeeze(abs(F.Parameters(1,2,:)))' ...
         squeeze(abs(F.Parameters(2,2,:)))' ...
         squeeze(angle(F.Parameters(1,1,:)))' ...
         squeeze(angle(F.Parameters(1,2,:)))' ...
         squeeze(angle(F.Parameters(2,2,:)))'];
    % U = [squeeze(abs(F.Parameters(1,1,:)))'...
    %      squeeze(abs(F.Parameters(1,2,:)))'...
    %      squeeze(abs(F.Parameters(2,2,:)))'];
    f = sqrt(mean((U-err).^2));
end