function f = synthesizeobj(x, sz, freqs, err)
    G = casctran(x, sz);
    H = tsc(G, sz);
    F = sparameters(freqresp(H,freqs),freqs);
    U = [real(squeeze(F.Parameters(1,1,:)))'...
         real(squeeze(F.Parameters(1,2,:)))'...
         real(squeeze(F.Parameters(2,2,:)))'...
         imag(squeeze(F.Parameters(1,1,:)))'...
         imag(squeeze(F.Parameters(1,2,:)))'...
         imag(squeeze(F.Parameters(2,2,:)))'];
    f = rmse(U,err);
end